project 'Kotlin.xcodeproj'
platform :ios, '10.0'

target 'Kotlin' do
  use_frameworks!

  pod 'MaterialComponents', '~> 113.1.0'
  pod 'Kingfisher', '~> 5.15.0'
  pod 'SnapKit', '~> 5.0.1'
  pod 'RxCocoa', '~> 5.1.1'
  pod 'common', :path => '../common'

  target 'KotlinTests' do
    inherit! :search_paths
  end

  target 'KotlinUITests' do
    inherit! :search_paths
  end

end
