project 'Kotlin.xcodeproj'
platform :ios, '9.0'

target 'Kotlin' do
  use_frameworks!

  pod 'MaterialComponents'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'common', :path => '../common'

  target 'KotlinTests' do
    inherit! :search_paths
  end

  target 'KotlinUITests' do
    inherit! :search_paths
  end

end
